# Default Configuration #

device: "cuda"

model:
  num_classes: 8
  architecture: efficientnet
  freeze_backbone: False
  dropout: 0.2
  hidden_units1: 100
  
  
train:
  batch_size: 32
  epochs: 10
  lr: 0.001
  momentum: 0.9
  optimizer: "sgd"
  criterion: "cross_entropy"

experiment:
  seed: 42
  experiment_name: "efficientnet"

transforms:
  resize: [224, 224]
  horizontal_flip: 0.5
  rotate: 15
  jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  custom:
    block_timestamp: true

log:
  img_count: 50
 



