# Default Configuration #

device: "mps"

model:
  num_classes: 8
  architecture: deit
  freeze_backbone: True
  dropout: 0.1
  hidden_units1: 256
  
train:
  batch_size: 8
  epochs: 2
  lr: 0.001
  momentum: 0.9
  optimizer: "adam"
  criterion: "focal"
  weight_decay: 0.02
  gamma: 3.0
  alpha: "reweight"
  # alpha: None

experiment:
  seed: 42
  experiment_name: deit_hidden_units

transforms:
  resize: [224,224]
  horizontal_flip: 0.5
  jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  custom:
    block_timestamp: True

log:
  img_count: 5
 



