# added focal loss #

device: "mps"

model:
  num_classes: 8
  architecture: resnet50
  freeze_backbone: False
  dropout: 0.1
  hidden_units1: 100
  

train:
  batch_size: 32
  epochs: 5
  lr: 0.1
  momentum: 0.9
  optimizer: "sgd"
  criterion: "focal"
  gamma: 2.0
  alpha: 0.5
  #alpha Weighting factor in range (0,1) to balance positive vs negative examples or -1 for ignore. Default: 0.25.
  #gamma Exponent of the modulating factor (1 - p_t) to balance easy vs hard examples. Default: 2.
  # g - focus on hard to classify
  # a - focus on minority
experiment:
  seed: 42
  experiment_name: "resnet50_focal"

transforms:
  resize: [224, 224]
  horizontal_flip: 0.5
  rotate: 15
  jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  custom:
    block_timestamp: True

log:
  img_count: 20
 



